name: Upload to DAFNI

on:
  release:
    types: [published]

jobs:
  release:
    name: Upload to DAFNI
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Decrypt CityCAT
        run: gpg --batch --output citycat.exe --passphrase ${{ secrets.CITYCAT_PASSPHRASE }} --decrypt citycat.exe.gpg

      - name: Docker Build
        run: docker build -t citycat-dafni .

      - name: Compress docker image
        run: docker save citycat-dafni | gzip > citycat-dafni.tar.gz

      - name: Set tag as env
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Upload to DAFNI
        uses: dafnifacility/dafni-model-uploader@v1.11
        with:
          definition-path: ./model-definition.yml
          image-path: ./citycat-dafni.tar.gz
          username: ${{ secrets.DAFNI_SERVICE_ACCOUNT_USERNAME }}
          password: ${{ secrets.DAFNI_SERVICE_ACCOUNT_PASSWORD }}
          version-message: ${{ env.TAG }}
          parent-model: "946a9072-bf7b-46e7-84c5-bb00ad5b88aa"
